# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_url', models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, verbose_name='manual URL')),
                ('anchor', models.CharField(blank=True, help_text='Appends the value only after the internal or external link. Do <em>not</em> include a preceding "#" symbol.', max_length=255, verbose_name='anchor')),
                ('mailto', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
            },
        ),
        migrations.CreateModel(
            name='UrlOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_url', models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, verbose_name='manual URL')),
                ('anchor', models.CharField(blank=True, help_text='Appends the value only after the internal or external link. Do <em>not</em> include a preceding "#" symbol.', max_length=255, verbose_name='anchor')),
                ('mailto', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_url_manager.Url')),
            ],
            options={
                'verbose_name': 'url override',
                'verbose_name_plural': 'url overrides',
            },
        ),
        migrations.CreateModel(
            name='UrlPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_url_manager_urlplugin', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('template', models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template')),
                ('target', models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Target')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_plugins', to='djangocms_url_manager.Url', verbose_name='url')),
            ],
            options={
                'verbose_name': 'url plugin model',
                'verbose_name_plural': 'url plugin models',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
