# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='internal_name',
            field=models.CharField(blank=True, help_text='This field can be used for searching URL', max_length=255, verbose_name='internal name'),
        ),
        migrations.AddField(
            model_name='urloverride',
            name='internal_name',
            field=models.CharField(blank=True, help_text='This field can be used for searching URL', max_length=255, verbose_name='internal name'),
        ),
        migrations.AlterField(
            model_name='url',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='urloverride',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
