# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0002_auto_20190218_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Provide a relative path to a web page or resource', max_length=2040, verbose_name='relative path'),
        ),
        migrations.AddField(
            model_name='urloverride',
            name='relative_path',
            field=models.CharField(blank=True, help_text='Provide a relative path to a web page or resource', max_length=2040, verbose_name='relative path'),
        ),
    ]
