# Generated by Django 2.2.12 on 2020-09-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0004_auto_20200114_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_urloverride_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='url',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_url_site', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='urloverride',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_urloverride_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='urloverride',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_urloverride_site', to='sites.Site'),
        ),
    ]
