# Generated by Django 2.2.24 on 2021-11-24 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0006_auto_20210513_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='linkplugin',
            name='internal_name',
        ),
        migrations.AddField(
            model_name='linkplugin',
            name='url_grouper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_url_manager_linkplugin_url_grouper', to='djangocms_url_manager.UrlGrouper'),
        ),
        migrations.AddField(
            model_name='url',
            name='url_grouper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_url_manager_url_url_grouper', to='djangocms_url_manager.UrlGrouper'),
        ),
    ]
