# Generated by Django 2.2.24 on 2021-11-12 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('djangocms_url_manager', '0006_auto_20210513_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('manual_url', models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, verbose_name='manual URL')),
                ('relative_path', models.CharField(blank=True, help_text='Provide a relative path to a web page or resource', max_length=2040, verbose_name='relative path')),
                ('anchor', models.CharField(blank=True, help_text='Appends the value only after the internal or external link. Do <em>not</em> include a preceding "#" symbol.', max_length=255, verbose_name='anchor')),
                ('mailto', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_urlgrouper_content_type', to='contenttypes.ContentType')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_urlgrouper_site', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='url',
            name='url_grouper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_url_manager_url_related', to='djangocms_url_manager.UrlGrouper'),
            preserve_default=False,
        ),
    ]
