# Generated by Django 2.2.24 on 2021-11-12 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0006_auto_20210513_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text='Provide internal name for URL objects for searching purpose', max_length=255, verbose_name='internal name')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='url_grouper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_url_manager_url_url_grouper', to='djangocms_url_manager.UrlGrouper'),
            preserve_default=False,
        ),
    ]
