# Generated by Django 2.2.24 on 2021-11-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_url_manager', '0007_auto_20211112_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkplugin',
            name='url_grouper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_url_manager_linkplugin_url_grouper', to='djangocms_url_manager.UrlGrouper'),
        ),
    ]
